version: '3'
services:
  app:
    build:
      context: .
    container_name: tera-editor
    restart: always
    ports:
      - '3500:80'
    command: ${COMMAND}
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    environment:
      - ENV=${ENV}
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
